# Generated by Django 5.2.13 on 2026-04-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensereport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expense Report', 'verbose_name_plural': 'Expense Reports'},
        ),
        migrations.AddField(
            model_name='expensereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
